### ISSUE TITLE
nodeos_run_test.py failed 

### ISSUE THREAD

**Issue by qwp-ryan** [EOSIO/eos#2426]
Here is my failed report:
"
launching bios
spawning child, programs/nodeos/nodeos --log-level-net-plugin debug  --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios
launching testnet_00
spawning child, programs/nodeos/nodeos --log-level-net-plugin debug  --config-dir etc/eosio/node_00 --data-dir var/lib/node_00
**********************************************************************
run 'bash bios_boot.sh' to kick off delegated block production
**********************************************************************
BEGIN
TEST_OUTPUT: test_output_0.txt
SERVER: localhost
PORT: 8888
 cmd: programs/eosio-launcher/eosio-launcher -k 15
 cmd: pkill nodeos
Stand up cluster
 cmd: programs/eosio-launcher/eosio-launcher -p 1 -n 1 -s mesh -d 1 -f --nodeos --log-level-net-plugin debug
  cmd: pgrep -fl nodeos
  psOut: "26730 python3
26738 nodeos
26739 nodeos
"
  ERROR: Failed to find nodeos pid. Pattern [
]?(\d+) (.* --data-dir var/lib/node_00)
 ERROR: Unable to validate nodeos instances, expected: 1, actual: 0
 FAILURE - launcher
 ERROR: Failed to stand up eos cluster.
Traceback (most recent call last):
  File "tests/nodeos_run_test.py", line 95, in <module>
    errorExit("Failed to stand up eos cluster.")
  File "/home/amax/eos/build/tests/testUtils.py", line 92, in errorExit
    exit(errorCode)
  File "/home/amax/Desktop/anaconda3/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/nodeos_run_test.py", line 627, in <module>
    cluster.dumpErrorDetails()
  File "/home/amax/eos/build/tests/testUtils.py", line 1874, in dumpErrorDetails
    fileName="etc/eosio/node_$02d/config.ini" % (i)
TypeError: not all arguments converted during string formatting
"
I think eos-launcher is something wrong. so I cheked with the command as following:
programs/nodeos/nodeos --log-level-net-plugin  debug --config-dir etc/eosio/node_00 --data-dir var/lib/node_00

and I got the wrong message:
"
2749615ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transaction
2749615ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transactions
2749615ms thread-0   account_history_api_plugin.cpp:45 plugin_startup       ] starting account_history_api_plugin
2749615ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_controlled_accounts
2749615ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_key_accounts
2749615ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_transaction
2749615ms thread-0   http_plugin.cpp:242           add_handler          ] add api url: /v1/account_history/get_transactions
2749618ms thread-0   main.cpp:97                   main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use
"

My OS is ubuntu 16.04 LTS, It is 32 cores server. I followed the instrunction on wiki
git clone https://github.com/EOSIO/eos --recursive

cd eos
./eosio_build.sh

Everything is OK!
But I cannot pass the test with 5 failed 
"
The following tests FAILED:
         26 - nodeos_run_test (Failed)
         27 - nodeos_run_remote_test (Failed)
         29 - nodeos_run_test-mongodb (Failed)
         30 - distributed-transactions-test (Failed)
         31 - distributed-transactions-remote-test (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8
"
The only missing package is 
"
 Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Doxygen not found.  Contract documentation will not be generated.
"

will somebody can help that?

**Comment by qwp-ryan** [comment]
rm eos
logout

redo! everything is OK!
