### ISSUE TITLE
nodeos_run_test-mongodb fails

### ISSUE THREAD

**Issue by xdengpao** [EOSIO/eos#2471]
Start 28: p2p_dawn515_test
28/31 Test #28: p2p_dawn515_test .......................   Passed    1.02 sec
      Start 29: nodeos_run_test-mongodb
29/31 Test #29: nodeos_run_test-mongodb ................***Failed    2.61 sec
      Start 30: distributed-transactions-test
30/31 Test #30: distributed-transactions-test ..........   Passed   38.82 sec
      Start 31: distributed-transactions-remote-test
31/31 Test #31: distributed-transactions-remote-test ...   Passed   56.02 sec
97% tests passed, 1 tests failed out of 31

Total Test time (real) = 396.72 sec

The following tests FAILED:
	 29 - nodeos_run_test-mongodb (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8

  =================================================================
  Contents of var/lib/node_00/stderr.txt:
1243131ms thread-0   chain_plugin.cpp:99           plugin_initialize    ] initializing chain plugin
1243131ms thread-0   chain_plugin.cpp:137          plugin_initialize    ] Resync requested: wiping database and blocks
1243131ms thread-0   mongo_db_plugin.cpp:803       plugin_initialize    ] initializing mongo_db_plugin
1243131ms thread-0   mongo_db_plugin.cpp:811       plugin_initialize    ] Resync requested: wiping mongo database on startup
1243131ms thread-0   mongo_db_plugin.cpp:821       plugin_initialize    ] connecting to mongodb://localhost:27017/EOStest
1243131ms thread-0   mongo_db_plugin.cpp:717       wipe_database        ] mongo db wipe_database
 =================================================================
== Errors see above ==
Shut down the cluster.
 cmd: programs/eosio-launcher/eosio-launcher -k 15
 cmd: pkill nodeos
Shut down the wallet.
 cmd: pkill keosd
Traceback (most recent call last):
  File "tests/nodeos_run_test.py", line 93, in <module>
    if cluster.launch(prodCount=prodCount) is False:
  File "/home/eos/eos/build/tests/testUtils.py", line 1198, in launch
    if not self.waitOnClusterBlockNumSync(1):
  File "/home/eos/eos/build/tests/testUtils.py", line 1318, in waitOnClusterBlockNumSync
    if node.doesNodeHaveBlockNum(targetHeadBlockNum) is False:
  File "/home/eos/eos/build/tests/testUtils.py", line 316, in doesNodeHaveBlockNum
    info=self.getInfo(silentErrors=True)
  File "/home/eos/eos/build/tests/testUtils.py", line 851, in getInfo
    trans=Node.runCmdReturnJson(cmd)
  File "/home/eos/eos/build/tests/testUtils.py", line 158, in runCmdReturnJson
    return jsonData
UnboundLocalError: local variable 'jsonData' referenced before assignment

**Comment by wuuzx** [comment]
Same problem with a empty var/lib

**Comment by dahifi** [comment]
Check the owner on 'programs/eosio-launcher/eosio-launcher'. I had same error and turned out that root was owner, not my user account. I believe it was caused by me running build as sudo. 

See my notes on #2464, I ran chown on my entire build dir and now I'm getting the jsonData error that you mentioned, but mine is on the nodeos_run_test.

**Comment by wuuzx** [comment]
Thank you for replay. But seems not my case

![image](https://user-images.githubusercontent.com/30622396/39028397-1017cfce-4489-11e8-9fa8-a23d0b629580.png)

**Comment by dahifi** [comment]
I've been having similar problems with the nodeos_run_test.py as well on both master and Dawn-v3.0.0. What version of Ubuntu are you running? Have you tried blowing out our eos directory and rebuilding from scratch?

**Comment by wuuzx** [comment]
Ubuntu 16.04.  Yes I have clone it from github and rebuilding from scrach. A previous build run test without any error, but encounter a bug later (can not compile sample contract), so I delete entire directory and clone a new version, then encouter this problem. any idea?

**Comment by xdengpao** [comment]
ubunt 16.04. I have rebuilded Dawn-v3.0.0 for two times, but it have the same problem.

**Comment by wuuzx** [comment]
this is a snapshot of error
![image](https://user-images.githubusercontent.com/30622396/39044183-0733a476-44c2-11e8-80aa-daf8ddd5a74b.png)

**Comment by reoxey** [comment]
I have exactly the same issue
```
  Node> Host: localhost, Port:8888
 Cluster viability smoke test. Validate every cluster node has block 1. 
         cmd: programs/cleos/cleos --host localhost --port 8888  --wallet-host localhost --wallet-port 8899 get info
          RAW > Failed to connect to nodeos at localhost:8888; is nodeos running?

          JSON> 

```

**Comment by amActiveHello** [comment]
sec@ll-B85M-DS3H-A:~/rgh/eos_719/eos/build/programs/cleos$ ./cleos create account eosio user  EOS7eanXtt1fx9sThAtg1pohi4bVVfHu2XanYaMjtxhtC65CV2S6q
Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?

**Comment by RyoNgs** [comment]
this is my solution. about nodeos_run_test-mongodb failed.

1. install mongo db core
-> $ sudo apt-get install mongodb-server-core
2. install mongo db client
-> $ sudo apt install mongodb-clients
3. test mongo db
-> eosio/build/tests/nodeos_run_test.py --mongod -v --dump-error-detail >& mongo_test.out
4. check log
-> vi eosio/build/mongo_test.out

![image](https://user-images.githubusercontent.com/41315919/43303276-f7c6ac88-91a9-11e8-8fae-7d2015540947.png)





5. build validation
-> $ ~/opt/mongodb/bin/mongod -f ~/opt/mongodb/mongod.conf &
-> $ cd eosio/build
-> make test

**Comment by MarcelBlockchain** [comment]
Just tried to run the test, seems they changed the args from --mongod to --mongodb. But somehow 'command not found' is still printed
