### ISSUE TITLE
Slim Segmentation fault on restart

### ISSUE THREAD

**Issue by jgiszczak** [EOSIO/eos#2858]
After running a non-producing node in a network for a while, shutting it down and attempting to restart fails.

Backtrace:

```#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:146
#1  0x00000000018b92f6 in SHA256_Update.part.0 ()
#2  0x00000000018b94ee in SHA256_Update ()
#3  0x0000000000732d8d in fc::raw::detail::if_class<fc::false_type>::pack<fc::sha256::encoder, unsigned int> (s=..., v=<optimized out>) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:379
#4  fc::raw::detail::if_reflected<fc::false_type>::pack<fc::sha256::encoder, unsigned int> (s=..., v=<optimized out>) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:416
#5  fc::raw::pack<fc::sha256::encoder, unsigned int> (s=..., v=<optimized out>) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:596
#6  fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> >::operator()<unsigned int, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul>, &eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul>::slot> (this=<optimized out>, 
    name=<optimized out>) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:345
#7  fc::reflector<eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> >::visit<fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > > (v=...) at /home/giszczakj/Dev/eos/libraries/chain/include/eosio/chain/block_timestamp.hpp:81
#8  fc::raw::detail::if_enum<fc::false_type>::pack<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > (s=..., v=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:391
#9  fc::raw::detail::if_reflected<fc::true_type>::pack<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > (s=..., v=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:427
#10 fc::raw::pack<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > (s=..., v=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:596
#11 fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_header>::operator()<eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul>, eosio::chain::block_header, &eosio::chain::block_header::timestamp> (this=0x7ffcecb35ea0, name=<optimized out>)
    at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:345
#12 fc::reflector<eosio::chain::block_header>::visit<fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_header> > (v=...) at /home/giszczakj/Dev/eos/libraries/chain/include/eosio/chain/block_header.hpp:58
#13 0x0000000000732d20 in fc::raw::detail::if_enum<fc::false_type>::pack<fc::sha256::encoder, eosio::chain::block_header> (s=..., v=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:391
#14 fc::raw::detail::if_reflected<fc::true_type>::pack<fc::sha256::encoder, eosio::chain::block_header> (s=..., v=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:427
#15 fc::raw::pack<fc::sha256::encoder, eosio::chain::block_header> (s=..., v=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/io/raw.hpp:596
#16 fc::sha256::hash<eosio::chain::block_header> (t=...) at /home/giszczakj/Dev/eos/libraries/fc/include/fc/crypto/sha256.hpp:31
#17 eosio::chain::block_header::digest (this=0x0) at /home/giszczakj/Dev/eos/libraries/chain/block_header.cpp:14
#18 eosio::chain::block_header::id (this=0x0) at /home/giszczakj/Dev/eos/libraries/chain/block_header.cpp:25
#19 0x0000000000792600 in eosio::chain::controller::get_block_id_for_num (this=0x3b801c0, block_num=4835) at /home/giszczakj/Dev/eos/libraries/chain/controller.cpp:1211
#20 0x000000000053e0d1 in eosio::handshake_initializer::populate (hello=...) at /home/giszczakj/Dev/eos/plugins/net_plugin/net_plugin.cpp:2739
#21 0x000000000053d6e3 in eosio::connection::send_handshake (this=0x3d64010) at /home/giszczakj/Dev/eos/plugins/net_plugin/net_plugin.cpp:905
#22 0x00000000005759e5 in eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10::operator()(boost::system::error_code const&) const (this=<optimized out>, err=...) at /home/giszczakj/Dev/eos/plugins/net_plugin/net_plugin.cpp:1950
```
Entirety of the corresponding log:

```2577089ms thread-0   chain_plugin.cpp:125          plugin_initialize    ] initializing chain plugin
2577089ms thread-0   block_log.cpp:120             open                 ] Log is nonempty
2577089ms thread-0   block_log.cpp:123             open                 ] my->head->block_num(): 4821 
2577090ms thread-0   block_log.cpp:129             open                 ] Index is nonempty
2577102ms thread-0   http_plugin.cpp:247           plugin_initialize    ] configured http to listen on 127.0.0.1:9002
2577102ms thread-0   net_plugin.cpp:2790           plugin_initialize    ] Initialize net plugin
2577102ms thread-0   net_plugin.cpp:2811           plugin_initialize    ] host: 0.0.0.0 port: 9899 
2577102ms thread-0   net_plugin.cpp:2883           plugin_initialize    ] my node_id is c9d682c33282974775257f2ec996dca4cf23fd2b206076a8fcbe0276cf091258
opened GELF socket to endpoint 35.192.235.199:12201
2577103ms thread-0   main.cpp:94                   main                 ] nodeos version 310dbd9e
2577103ms thread-0   main.cpp:95                   main                 ] eosio root is /home/giszczakj/.local/share
2577103ms thread-0   chain_plugin.cpp:253          plugin_startup       ] starting chain in read/write mode
2577103ms thread-0   chain_plugin.cpp:258          plugin_startup       ] Blockchain started; head block is #4843, genesis timestamp is 2018-04-24T00:00:00.000
2577103ms thread-0   http_plugin.cpp:285           plugin_startup       ] start listening for http requests
2577103ms thread-0   chain_api_plugin.cpp:62       plugin_startup       ] starting chain_api_plugin
2577103ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/abi_bin_to_json
2577103ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/abi_json_to_bin
2577103ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_account
2577103ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_block
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_code
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_currency_balance
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_currency_stats
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_info
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_required_keys
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/get_table_rows
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/push_block
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/push_transaction
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/chain/push_transactions
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/txn_test_gen/create_test_accounts
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/txn_test_gen/start_generation
2577104ms thread-0   http_plugin.cpp:325           add_handler          ] add api url: /v1/txn_test_gen/stop_generation
2577105ms thread-0   net_plugin.cpp:2895           plugin_startup       ] starting listener, max clients is 25
2577105ms thread-0   net_plugin.cpp:678            connection           ] created connection to 127.0.0.4:9901
2577105ms thread-0   net_plugin.cpp:1923           connect              ] host: 127.0.0.4 port: 9901 
2577105ms thread-0   producer_plugin.cpp:310       plugin_startup       ] producer plugin:  plugin_startup() begin
2577105ms thread-0   producer_plugin.cpp:317       plugin_startup       ] Launching block production for 1 producers.
2577105ms thread-0   producer_plugin.cpp:380       start_block          ] 10 assert_exception: Assert Exception
db.revision() == head->block_num: 
    {"db.revision()":4844,"controller_head_block":4843,"fork_db_head_block":4843}
    thread-0  controller.cpp:659 start_block
2577105ms thread-0   producer_plugin.cpp:409       schedule_production_ ] Failed to start a pending block, will try again later
2577105ms thread-0   producer_plugin.cpp:328       plugin_startup       ] producer plugin:  plugin_startup() end
```

Frame #19 in the backtrace says it's attempting to retrieve block number 4835 but on startup, the chain plugin claimed the head block number is 4821.  Frame #19 is the net_plugin trying to use the `last_irreversible_block_num();` it just retrieved from the chain controller, a number that's ahead of the head block.

**Comment by bytemaster** [comment]
When nodeos shuts down it should print the block numbers of forkdb, block log, and chainbase.  

It looks like the pending block needs to be aborted when shutting down.
