### ISSUE TITLE
core on restart of nodeos

### ISSUE THREAD

**Issue by heifner** [EOSIO/eos#2963]
With a restart of nodeos (not replay or resync) a core is generated.

```
(gdb) where
#0  0x00007f5a27b37b64 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000001ebb4d3 in SHA256_Update ()
#2  0x0000000000fb6e1b in fc::sha256::encoder::write (this=0x7ffecc486528, d=0x0, dlen=4) at /home/heifnerk/ext/eosio/libraries/fc/src/crypto/sha256.cpp:57
#3  0x000000000088fdd2 in fc::raw::detail::if_class<fc::false_type>::pack<fc::sha256::encoder, unsigned int> (s=..., v=<error reading variable>) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:379
#4  0x000000000088fd9d in fc::raw::detail::if_reflected<fc::false_type>::pack<fc::sha256::encoder, unsigned int> (s=..., v=<error reading variable>) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:416
#5  0x000000000088fd6d in fc::raw::pack<fc::sha256::encoder, unsigned int> (s=..., v=<error reading variable>) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:596
#6  0x00000000008954d0 in fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> >::operator()<unsigned int, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul>, &eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul>::slot> (this=0x7ffecc4863e0, name=0x232df38 "slot") at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:345
#7  0x000000000089546f in fc::reflector<eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> >::visit<fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > > (v=...) at /home/heifnerk/ext/eosio/libraries/chain/include/eosio/chain/block_timestamp.hpp:81
#8  0x000000000089543d in fc::raw::detail::if_enum<fc::false_type>::pack<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > (s=..., v=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:391
#9  0x00000000008953fd in fc::raw::detail::if_reflected<fc::true_type>::pack<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > (s=..., v=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:427
#10 0x00000000008953cd in fc::raw::pack<fc::sha256::encoder, eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul> > (s=..., v=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:596
#11 0x0000000000895220 in fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_header>::operator()<eosio::chain::block_timestamp<(unsigned short)500, 946684800000ul>, eosio::chain::block_header, &eosio::chain::block_header::timestamp> (this=0x7ffecc486490, name=0x269b4f0 "timestamp") at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:345
#12 0x000000000089511f in fc::reflector<eosio::chain::block_header>::visit<fc::raw::detail::pack_object_visitor<fc::sha256::encoder, eosio::chain::block_header> > (v=...) at /home/heifnerk/ext/eosio/libraries/chain/include/eosio/chain/block_header.hpp:58
#13 0x00000000008950ed in fc::raw::detail::if_enum<fc::false_type>::pack<fc::sha256::encoder, eosio::chain::block_header> (s=..., v=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:391
#14 0x00000000008950ad in fc::raw::detail::if_reflected<fc::true_type>::pack<fc::sha256::encoder, eosio::chain::block_header> (s=..., v=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:427
#15 0x000000000089507d in fc::raw::pack<fc::sha256::encoder, eosio::chain::block_header> (s=..., v=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/io/raw.hpp:596
#16 0x0000000000895003 in fc::sha256::hash<eosio::chain::block_header> (t=...) at /home/heifnerk/ext/eosio/libraries/fc/include/fc/crypto/sha256.hpp:31
#17 0x0000000000894e4c in eosio::chain::block_header::digest (this=0x0) at /home/heifnerk/ext/eosio/libraries/chain/block_header.cpp:14
#18 0x0000000000894eb4 in eosio::chain::block_header::id (this=0x0) at /home/heifnerk/ext/eosio/libraries/chain/block_header.cpp:25
#19 0x00000000008fdac1 in eosio::chain::controller::get_block_id_for_num (this=0x3aa85d0, block_num=22684) at /home/heifnerk/ext/eosio/libraries/chain/controller.cpp:1192
#20 0x000000000059cd71 in eosio::handshake_initializer::populate (hello=...) at /home/heifnerk/ext/eosio/plugins/net_plugin/net_plugin.cpp:2752
#21 0x000000000059c50b in eosio::connection::send_handshake (this=0x3b8fbb0) at /home/heifnerk/ext/eosio/plugins/net_plugin/net_plugin.cpp:909
#22 0x00000000005cc5cc in eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10::operator()(boost::system::error_code const&) const (this=0x7ffecc487378, err=...) at /home/heifnerk/ext/eosio/plugins/net_plugin/net_plugin.cpp:1963
#23 0x00000000005cc52f in boost::asio::detail::binder1<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10(boost::system::error_code)>::operator()() (this=0x7ffecc487378) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/bind_handler.hpp:65
#24 0x00000000005cc4e5 in boost::asio::asio_handler_invoke<boost::asio::detail::binder1<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10(boost::system::error_code)> >(boost::asio::detail::binder1<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10(boost::system::error_code)>&, ...) (function=...) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/handler_invoke_hook.hpp:69
#25 0x00000000005cc4c2 in boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder1<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10(boost::system::error_code)>, boost::system>(boost::asio::detail::binder1<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10(boost::system::error_code)>&, boost::system&) (function=..., context=...) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#26 0x00000000005cd371 in boost::asio::detail::handler_work<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10(boost::asio::system_executor)>::complete<boost::asio::detail::binder1<boost::asio::system_executor, boost::system::error_code> >(boost::asio::detail::binder1<boost::asio::system_executor, boost::system::error_code>&, boost::asio::system_executor&) (this=0x7ffecc4873b8, function=..., handler=...) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/handler_work.hpp:82
#27 0x00000000005cd173 in boost::asio::detail::reactive_socket_connect_op<eosio::net_plugin_impl::connect(std::shared_ptr<eosio::connection>, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>)::$_10>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x3aa8170, base=0x3b2c5d0) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/reactive_socket_connect_op.hpp:100
#28 0x000000000047bae7 in boost::asio::detail::scheduler_operation::complete (this=0x3b2c5d0, owner=0x3aa8170, ec=..., bytes_transferred=0) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/scheduler_operation.hpp:40
#29 0x000000000047b864 in boost::asio::detail::epoll_reactor::descriptor_state::do_complete (owner=0x3aa8170, base=0x3b3a5a0, ec=..., bytes_transferred=4) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/impl/epoll_reactor.ipp:776
#30 0x000000000047bae7 in boost::asio::detail::scheduler_operation::complete (this=0x3b3a5a0, owner=0x3aa8170, ec=..., bytes_transferred=4) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/scheduler_operation.hpp:40
#31 0x000000000048fc85 in boost::asio::detail::scheduler::do_run_one (this=0x3aa8170, lock=..., this_thread=..., ec=...) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/impl/scheduler.ipp:401
#32 0x000000000048f791 in boost::asio::detail::scheduler::run (this=0x3aa8170, ec=...) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/detail/impl/scheduler.ipp:154
#33 0x000000000048d241 in boost::asio::io_context::run (this=0x3aa8100) at /home/heifnerk/opt/boost_1_67_0/include/boost/asio/impl/io_context.ipp:62
#34 0x000000000048a6cd in appbase::application::exec (this=0x318af00 <appbase::application::instance()::_app>) at /home/heifnerk/ext/eosio/libraries/appbase/application.cpp:225
#35 0x000000000046fe7f in main (argc=9, argv=0x7ffecc488108) at /home/heifnerk/ext/eosio/programs/nodeos/main.cpp:97
#36 0x00007f5a279cab97 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by heifner** [comment]
Resolved by #2966
