### ISSUE TITLE
Test #30 - nodeos_run_test - fails --> unrecognised option '--mongodb-uri'

### ISSUE THREAD

**Issue by acoutts** [EOSIO/eos#4194]
After pulling the latest from 'master' and running the build script I attempted to run build_test. All tests passed except for #30 - nodeos_run_test.

Computer: Macbook Pro Mid 2014
macOS High Sierra v10.13.5

Output is as follows:
```
andrewcoutts@Andrews-MacBook-Pro:~/Projects/eoshome/eos/build$ make test
Running tests...
Test project /Users/andrewcoutts/Projects/eoshome/eos/build
      Start  1: test_cypher_suites
 1/36 Test  #1: test_cypher_suites ...................   Passed    0.07 sec
      Start  2: validate_simple.token_abi
 2/36 Test  #2: validate_simple.token_abi ............   Passed    0.10 sec
      Start  3: validate_eosio.token_abi
 3/36 Test  #3: validate_eosio.token_abi .............   Passed    0.07 sec
      Start  4: validate_eosio.msig_abi
 4/36 Test  #4: validate_eosio.msig_abi ..............   Passed    0.06 sec
      Start  5: validate_multi_index_test_abi
 5/36 Test  #5: validate_multi_index_test_abi ........   Passed    0.06 sec
      Start  6: validate_eosio.system_abi
 6/36 Test  #6: validate_eosio.system_abi ............   Passed    0.07 sec
      Start  7: validate_identity_abi
 7/36 Test  #7: validate_identity_abi ................   Passed    0.06 sec
      Start  8: validate_identity_test_abi
 8/36 Test  #8: validate_identity_test_abi ...........   Passed    0.06 sec
      Start  9: validate_stltest_abi
 9/36 Test  #9: validate_stltest_abi .................   Passed    0.06 sec
      Start 10: validate_exchange_abi
10/36 Test #10: validate_exchange_abi ................   Passed    0.06 sec
      Start 11: validate_test.inline_abi
11/36 Test #11: validate_test.inline_abi .............   Passed    0.06 sec
      Start 12: validate_hello_abi
12/36 Test #12: validate_hello_abi ...................   Passed    0.06 sec
      Start 13: validate_asserter_abi
13/36 Test #13: validate_asserter_abi ................   Passed    0.07 sec
      Start 14: validate_infinite_abi
14/36 Test #14: validate_infinite_abi ................   Passed    0.06 sec
      Start 15: validate_proxy_abi
15/36 Test #15: validate_proxy_abi ...................   Passed    0.07 sec
      Start 16: validate_test_api_abi
16/36 Test #16: validate_test_api_abi ................   Passed    0.06 sec
      Start 17: validate_test_api_mem_abi
17/36 Test #17: validate_test_api_mem_abi ............   Passed    0.06 sec
      Start 18: validate_test_api_db_abi
18/36 Test #18: validate_test_api_db_abi .............   Passed    0.06 sec
      Start 19: validate_test_api_multi_index_abi
19/36 Test #19: validate_test_api_multi_index_abi ....   Passed    0.06 sec
      Start 20: validate_test_ram_limit_abi
20/36 Test #20: validate_test_ram_limit_abi ..........   Passed    0.06 sec
      Start 21: validate_eosio.bios_abi
21/36 Test #21: validate_eosio.bios_abi ..............   Passed    0.06 sec
      Start 22: validate_noop_abi
22/36 Test #22: validate_noop_abi ....................   Passed    0.07 sec
      Start 23: validate_dice_abi
23/36 Test #23: validate_dice_abi ....................   Passed    0.06 sec
      Start 24: validate_tic_tac_toe_abi
24/36 Test #24: validate_tic_tac_toe_abi .............   Passed    0.07 sec
      Start 25: validate_payloadless_abi
25/36 Test #25: validate_payloadless_abi .............   Passed    0.07 sec
      Start 26: unit_test_binaryen
26/36 Test #26: unit_test_binaryen ...................   Passed  187.57 sec
      Start 27: unit_test_wavm
27/36 Test #27: unit_test_wavm .......................   Passed  670.29 sec
      Start 28: validate_deferred_test_abi
28/36 Test #28: validate_deferred_test_abi ...........   Passed    0.11 sec
      Start 29: plugin_test
29/36 Test #29: plugin_test ..........................   Passed    0.05 sec
      Start 30: nodeos_run_test
30/36 Test #30: nodeos_run_test ......................***Failed   49.33 sec
      Start 31: p2p_dawn515_test
31/36 Test #31: p2p_dawn515_test .....................   Passed    8.49 sec
      Start 32: distributed-transactions-test
32/36 Test #32: distributed-transactions-test ........   Passed   73.52 sec
      Start 33: restart-scenarios-test-resync
33/36 Test #33: restart-scenarios-test-resync ........   Passed  147.18 sec
      Start 34: restart-scenarios-test-hard_replay
34/36 Test #34: restart-scenarios-test-hard_replay ...   Passed  154.57 sec
      Start 35: restart-scenarios-test-none
35/36 Test #35: restart-scenarios-test-none ..........   Passed  147.27 sec
      Start 36: validate_dirty_db_test
36/36 Test #36: validate_dirty_db_test ...............   Passed    2.90 sec

97% tests passed, 1 tests failed out of 36

Total Test time (real) = 1443.06 sec

The following tests FAILED:
	 30 - nodeos_run_test (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Next I tried running that test again to capture the output:
```
andrewcoutts@Andrews-MacBook-Pro:~/Projects/eoshome/eos/build$ tests/nodeos_run_test.py --mongodb -v --dump-error-detail >& mongo_test.out
```

Here is the output generated from that test:
```
kill: 18956: No such process
kill: 18957: No such process
launching bios
spawning child, programs/nodeos/nodeos --max-transaction-time 5000 --filter-on * --p2p-max-nodes-per-host 1  --delete-all-blocks   --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios --genesis-json ./genesis.json --genesis-timestamp 2018-06-18T16:17:57.219
launching testnet_00
spawning child, programs/nodeos/nodeos --max-transaction-time 5000 --filter-on * --p2p-max-nodes-per-host 1 --plugin eosio::mongo_db_plugin --delete-all-blocks --mongodb-uri mongodb://localhost:27017/EOStest  --config-dir etc/eosio/node_00 --data-dir var/lib/node_00 --genesis-json ./genesis.json --genesis-timestamp 2018-06-18T16:17:57.219
**********************************************************************
run 'bash bios_boot.sh' to kick off delegated block production
**********************************************************************
kill: 19018: No such process
BEGIN
SERVER: localhost
PORT: 8888
 echo db.version() | mongo --host localhost --port 27017 EOStest
 MongoDb response: b'MongoDB shell version v3.6.5\nconnecting to: mongodb://localhost:27017/EOStest\nMongoDB server version: 3.6.5\n3.6.5\nbye\n'
 cmd: programs/eosio-launcher/eosio-launcher -k 9
 echo db.dropDatabase() | mongo --host localhost --port 27017 EOStest
Stand up cluster
 cmd: programs/eosio-launcher/eosio-launcher -p 1 -n 1 -s mesh -d 1 -i 2018-06-18T16:17:57.219 -f --p2p-plugin net --nodeos --max-transaction-time 5000 --filter-on * --p2p-max-nodes-per-host 1 --plugin eosio::mongo_db_plugin --delete-all-blocks --mongodb-uri mongodb://localhost:27017/EOStest
    cmd: pgrep -fl nodeos
  pgrep output: "19017 programs/nodeos/nodeos --max-transaction-time 5000 --filter-on * --p2p-max-nodes-per-host 1 --delete-all-blocks --config-dir etc/eosio/node_bios --data-dir var/lib/node_bios --genesis-json ./genesis.json --genesis-timestamp 2018-06-18T16:17:57.219
"
  ERROR: Failed to find nodeos pid. Pattern [\n]?(\d+) (.* --data-dir var/lib/node_00 .*)\n
 ERROR: Unable to validate nodeos instances, expected: 1, actual: 0
 FAILURE - launcher
 ERROR: Failed to stand up eos cluster.
 Test failed.
   =================================================================
   Contents of etc/eosio/node_bios/config.ini:
blocks-dir = blocks
readonly = 0
send-whole-blocks = true
http-server-address = 127.0.0.1:8788
p2p-listen-endpoint = 0.0.0.0:9776
p2p-server-address = localhost:9776
enable-stale-production = true
allowed-connection = any
private-key = ["EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"]
producer-name = eosio
plugin = eosio::producer_plugin
plugin = eosio::net_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::history_api_plugin
   =================================================================
   Contents of var/lib/node_bios/stderr.txt:
1077283ms thread-0   chain_plugin.cpp:208          plugin_initialize    ] initializing chain plugin
1077283ms thread-0   chain_plugin.cpp:312          plugin_initialize    ] Deleting state database and blocks
1077283ms thread-0   chain_plugin.cpp:375          plugin_initialize    ] Using genesis state provided in '/Users/andrewcoutts/Projects/eoshome/eos/build/./genesis.json'
1077283ms thread-0   chain_plugin.cpp:200          calculate_genesis_ti ] pausing 281000 microseconds to the next interval
1077283ms thread-0   chain_plugin.cpp:203          calculate_genesis_ti ] Adjusting genesis timestamp to 2018-06-18T16:17:57.500
1077284ms thread-0   chain_plugin.cpp:381          plugin_initialize    ] Starting up fresh blockchain with provided genesis state.
1077873ms thread-0   producer_plugin.cpp:508       plugin_initialize    ] "private-key" is DEPRECATED, use "signature-provider=EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV=KEY:***************************************************"
1077874ms thread-0   net_plugin.cpp:2948           plugin_initialize    ] Initialize net plugin
1077874ms thread-0   net_plugin.cpp:2972           plugin_initialize    ] host: 0.0.0.0 port: 9776 
1077874ms thread-0   net_plugin.cpp:3044           plugin_initialize    ] my node_id is 8484813890a13b2676b98d18df6a2ac576ae94a2da6af28bd4912188b7d3a2a1
1077874ms thread-0   http_plugin.cpp:290           plugin_initialize    ] configured http to listen on 127.0.0.1:8788
1077875ms thread-0   history_plugin.cpp:275        plugin_initialize    ] --filter-on * enabled. This can fill shared_mem, causing nodeos to stop.
opened GELF socket to endpoint 10.160.11.21:12201
1077875ms thread-0   main.cpp:104                  main                 ] nodeos version b8f17f2e
1077875ms thread-0   main.cpp:105                  main                 ] eosio root is /Users/andrewcoutts/Library/Application Support
1077876ms thread-0   controller.cpp:1190           startup              ] No head block in fork db, perhaps we need to replay
1077876ms thread-0   controller.cpp:304            initialize_fork_db   ]  Initializing new blockchain with genesis state                  
1077903ms thread-0   chain_plugin.cpp:446          plugin_startup       ] starting chain in read/write mode
1077903ms thread-0   chain_plugin.cpp:451          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-18T16:17:57.500
1077904ms thread-0   producer_plugin.cpp:577       plugin_startup       ] producer plugin:  plugin_startup() begin
1077904ms thread-0   producer_plugin.cpp:592       plugin_startup       ] Launching block production for 1 producers at 2018-06-18T16:17:57.904.
1077905ms thread-0   producer_plugin.cpp:604       plugin_startup       ] producer plugin:  plugin_startup() end
1077905ms thread-0   net_plugin.cpp:3056           plugin_startup       ] starting listener, max clients is 25
1077905ms thread-0   http_plugin.cpp:331           plugin_startup       ] start listening for http requests
1077905ms thread-0   chain_api_plugin.cpp:75       plugin_startup       ] starting chain_api_plugin
1077905ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_bin_to_json
1077905ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/abi_json_to_bin
1077905ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_abi
1077905ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_account
1077905ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_block
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_block_header_state
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_code
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_currency_balance
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_currency_stats
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_info
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_producers
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_required_keys
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/get_table_rows
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_block
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transaction
1077906ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/chain/push_transactions
1077907ms thread-0   history_api_plugin.cpp:38     plugin_startup       ] starting history_api_plugin
1077907ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_actions
1077907ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_controlled_accounts
1077907ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_key_accounts
1077907ms thread-0   http_plugin.cpp:377           add_handler          ] add api url: /v1/history/get_transaction
1078004ms thread-0   net_plugin.cpp:2738           accepted_block_heade ] signaled, id = 00000002f5a2e8348f853709b507aff00b569a9faa2813b0a8d7dac8e4fddba2
1078004ms thread-0   net_plugin.cpp:2742           accepted_block       ] signaled, id = 00000002f5a2e8348f853709b507aff00b569a9faa2813b0a8d7dac8e4fddba2
1078005ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00000002f5a2e834... #2 @ 2018-06-18T16:17:58.000 signed by eosio [trxs: 0, lib: 0, confirmed: 0]
1078005ms thread-0   net_plugin.cpp:2751           accepted_transaction ] signaled, id = 1e71f2c73ce327739cb2fd5896be4bc4d154c582fabdf72473d40152a472abb4
1078005ms thread-0   net_plugin.cpp:2756           applied_transaction  ] signaled, id = 1e71f2c73ce327739cb2fd5896be4bc4d154c582fabdf72473d40152a472abb4
1078502ms thread-0   net_plugin.cpp:2747           irreversible_block   ] signaled, id = 000000013011624bae0fcbbcf8b6f1116a0d31734f4be2d9c2e878bd160f2ee4
1078503ms thread-0   net_plugin.cpp:2738           accepted_block_heade ] signaled, id = 00000003ecb4c594e587cf4171543cbcb95bd75364ea03b5e7ed0222adbd193f
1078503ms thread-0   net_plugin.cpp:2742           accepted_block       ] signaled, id = 00000003ecb4c594e587cf4171543cbcb95bd75364ea03b5e7ed0222adbd193f
1078503ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00000003ecb4c594... #3 @ 2018-06-18T16:17:58.500 signed by eosio [trxs: 0, lib: 2, confirmed: 0]
1078503ms thread-0   net_plugin.cpp:2751           accepted_transaction ] signaled, id = 9df693002f0c02da8f04733b704806c615a092653269d23dbbe2db1f8b320d17
1078504ms thread-0   net_plugin.cpp:2756           applied_transaction  ] signaled, id = 9df693002f0c02da8f04733b704806c615a092653269d23dbbe2db1f8b320d17
1079002ms thread-0   net_plugin.cpp:2747           irreversible_block   ] signaled, id = 00000002f5a2e8348f853709b507aff00b569a9faa2813b0a8d7dac8e4fddba2
1079003ms thread-0   net_plugin.cpp:2738           accepted_block_heade ] signaled, id = 00000004ffaa3f45a5c2ad80599fe7e178253852105d91fa44734abe26273df4
1079004ms thread-0   net_plugin.cpp:2742           accepted_block       ] signaled, id = 00000004ffaa3f45a5c2ad80599fe7e178253852105d91fa44734abe26273df4
1079004ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 00000004ffaa3f45... #4 @ 2018-06-18T16:17:59.000 signed by eosio [trxs: 0, lib: 3, confirmed: 0]
1079004ms thread-0   net_plugin.cpp:2751           accepted_transaction ] signaled, id = 7ad53f3ecf4745c14e62784bfa4a7c3d7f19bf17eab05c38772911a9e8c3c245
1079005ms thread-0   net_plugin.cpp:2756           applied_transaction  ] signaled, id = 7ad53f3ecf4745c14e62784bfa4a7c3d7f19bf17eab05c38772911a9e8c3c245
   =================================================================
   Contents of etc/eosio/node_00/config.ini:
blocks-dir = blocks
readonly = 0
send-whole-blocks = true
http-server-address = 127.0.0.1:8888
p2p-listen-endpoint = 0.0.0.0:9876
p2p-server-address = localhost:9876
allowed-connection = any
p2p-peer-address = localhost:9776
private-key = ["EOS6AbcD6ht3jhRfUhuWHmi9XBRm3MaoqdbnWKhdQVo8oPn4bV7wM","5J6Src3n5MBW46Gmu1ikBdy677ywNt3xnMrypsiXucbQ8pGErqx"]
producer-name = defproducera
producer-name = defproducerb
producer-name = defproducerc
producer-name = defproducerd
producer-name = defproducere
producer-name = defproducerf
producer-name = defproducerg
producer-name = defproducerh
producer-name = defproduceri
producer-name = defproducerj
producer-name = defproducerk
producer-name = defproducerl
producer-name = defproducerm
producer-name = defproducern
producer-name = defproducero
producer-name = defproducerp
producer-name = defproducerq
producer-name = defproducerr
producer-name = defproducers
producer-name = defproducert
producer-name = defproduceru
plugin = eosio::producer_plugin
plugin = eosio::net_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::history_api_plugin
   =================================================================
   Contents of var/lib/node_00/stderr.txt:
1078287ms thread-0   main.cpp:119                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option '--mongodb-uri'

  =================================================================
 == Errors see above ==
 Shut down the cluster.
  cmd: programs/eosio-launcher/eosio-launcher -k 9
Traceback (most recent call last):
  File "tests/nodeos_run_test.py", line 75, in <module>
    errorExit("Failed to stand up eos cluster.")
  File "/Users/andrewcoutts/Projects/eoshome/eos/build/tests/testUtils.py", line 87, in errorExit
    exit(errorCode)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/nodeos_run_test.py", line 772, in <module>
    TestHelper.shutdown(cluster, walletMgr, testSuccessful, killEosInstances, killWallet, keepLogs, killAll, dumpErrorDetails)
  File "/Users/andrewcoutts/Projects/eoshome/eos/build/tests/TestHelper.py", line 110, in shutdown
    cluster.killall(allInstances=cleanRun)
  File "/Users/andrewcoutts/Projects/eoshome/eos/build/tests/Cluster.py", line 956, in killall
    if node.pid is not None:
AttributeError: 'int' object has no attribute 'pid'
```

**Comment by jgiszczak** [comment]
Work is ongoing to bring the mongodb_plugin and associated tests back up to date.  Issue #3030 is being updated with projected release dates.

**Comment by acoutts** [comment]
Thanks @jgiszczak

**Comment by cj-oci** [comment]
Hi, the test you ran (with mongodb plugin) is currently disabled. You can run just the nodeos_run_test via:

ctest --output-on-failure -R 'nodeos_run_test'
