### ISSUE TITLE
Occured "ECONNRESET" exception when calling RPC:push_transaction with node.js

### ISSUE THREAD

**Issue by vincentwang0736** [EOSIO/eos#4688]
I got "ECONNRESET" exception when calling RPC:push_transaction  with node.js and the former step "sign_transaction" is ok.

> Here is code:
> var signStr = "[{\"ref_block_num\":" + block_num + ",\"ref_block_prefix\":" + ref_block_prefix + ",\"expiration\":\"" + expiration + "\",\"actions\":[{\"account\":\"eosio\",\"name\":\"newaccount\",\"authorization\":[{\"actor\":\"" + creater_name + "\",\"permission\":\"active\"}],\"data\":\"" + binargs + "\"}],\"signatures\":[]},[\"" + creater_pubkey + "\"],\"\"]"
>                                         signTx(signStr,(result_signTx) => {
>                                             var producer_signature = result_signTx.signatures[0];
>                                             if (producer_signature) {
>                                                 var pushTxStr = "{'context_free_data':[],'transaction':{'expiration':'" + expiration + "','delay_sec':0,'ref_block_num':" + block_num + ",'ref_block_prefix':" + ref_block_prefix + ",'context_free_actions':[],'actions':[{'data':'" + binargs + "','authorization':[{'permission':'active','actor':'" + creater_name + "'}],'account':'eosio','name':'newaccount'}]},'compression':'none','signatures':['" + producer_signature + "']}";
>                                                 pushTx(pushTxStr,(result_pushTx) => {
>                                                     response_generNewAccount.json(result_pushTx);
> });

........
.........

> function pushTx(jsonStr, callback) {
>     var post_data = {
>         host: '127.0.0.1',
>         port: 8888,
>         path: '/v1/chain/push_transaction',
>         method: 'POST',
>         headers: {
>             'Content-Type': 'application/json',
>             'Content-Length': Buffer.byteLength(jsonStr)
>         }
>     };
> 
>     var req = http.request(post_data, (res) => {
>         res.setEncoding('utf8');
>         res.on('data', (res_data) => {
>             result = JSON.parse(res_data);
>             callback(result);
>         });
>     });
>     req.on('error', function (e) {
>         callback(e);
>     });
> 
>     req.write(jsonStr);
>     req.end();
> }

And here is the exception I got:
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: socket hang up
>     at createHangUpError (_http_client.js:331:15)
>     at Socket.socketOnEnd (_http_client.js:423:23)
>     at emitNone (events.js:111:20)
>     at Socket.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

> {"code":"ECONNRESET"}

Can anyone help me?Thanks a lot!

**Comment by vincentwang0736** [comment]
Can anyone help me?
