### ISSUE TITLE
Occur error at contract demo used eosjs

### ISSUE THREAD

**Issue by vincentwang0736** [EOSIO/eos#5301]
I wrote a demo for publishing contract,here is my code:

> os = require('eosjs')
> const fs = require('fs');
> let {ecc} = Eos.modules
> 
> initaPrivate = '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3';//inita私钥
> 
> currencyPrivate = ecc.seedPrivate('currency');
> currencyPublic  = ecc.privateToPublic(currencyPrivate);
> 
> keyProvider     = [initaPrivate, currencyPrivate];
> 
> binaryen = require('binaryen');//导入编译器
> 
> eos = Eos.Localnet({keyProvider, binaryen});
> 
> eos.newaccount({
>     creator:    'eosio',
>     name:       'currency',
>     owner:      currencyPublic,
>     active:     currencyPublic,
>     recovery:   'eosio'
> });
> 
> contractDir = `/opt/eos/build/contracts/eosio.token`; //合约所在目录
> wast = fs.readFileSync(`${contractDir}/eosio.token.wast`);//读取wast文件，wast文
> 件通过eosiocpp编译
> abi  = fs.readFileSync(`${contractDir}/eosio.token.abi`);//读取abi文件
> 
> //将智能合约发不到区块链
> eos.setcode('currency', 0, 0, wast);
> eos.setabi('currency', JSON.parse(abi));
> 
> currency = null;
> // eos.contract(account<string>, [options], [callback]);
> eos.contract('currency').then(contract => currency = contract);//部署合约
> 
> // 让inita账户执行该合约，并发行一个代币CUR
> currency.issue('eosio', '10000.0000 CUR', {authorization: 'currency'});

But when I node this js file,I got these error:

> /etc/projects/eos/eosjspro/node_modules/binaryen/index.js:26
> typeof module&&(module.exports=a);process.on("uncaughtException",function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?
>                                                                                                    ^
> 
> TypeError: Cannot read property 'issue' of null
>     at Object.<anonymous> (/etc/projects/eos/eosjspro/eosjs_contract_demo.js:37:10)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:612:3

Anyone can help me or give me some advices? Thanks a lot!

**Comment by jgiszczak** [comment]
Problems like this are best filed with https://github.com/EOSIO/eosjs

**Comment by wuyahuang** [comment]
I think you can't issue token before contract have been deployed successfully.

eos.contract('currency').then(function(contract){
    currency = contract
    currency.issue('eosio', '10000.0000 CUR', {authorization: 'currency'});
});
