### ISSUE TITLE
airship-in-a-bottle single node fails

### ISSUE THREAD

**Issue by swainamar** [EOSIO/eos#7498]
The airship-in-a-bottle single node deployment failing with the following error. 

2019-06-13 15:10:10,928 WARNING  req_id=- ctx=- end_user=- user=- promenade.tar_bundler:tar_bundler.py: 38:add Zero length file added to path=etc/apt/sources.list.d/promenade-sources.list
2019-06-13 15:10:11,803 ERROR    req_id=- ctx=- end_user=- user=- promenade.renderer:renderer.py: 78:render_template_into_bundler Error rendering template (/opt/promenade/promenade/templates/roles/genesis/etc/kubernetes/manifests/bootstrap-armada.yaml)
Traceback (most recent call last):
  File "/opt/promenade/promenade/renderer.py", line 76, in render_template_into_bundler
    data = template.render(config=config, now=now)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 120, in top-level template code
jinja2.exceptions.UndefinedError: No match found for path HostSystem:images.monitoring_image
2019-06-13 15:10:11,804 ERROR    req_id=- ctx=- end_user=- user=- promenade.exceptions:exceptions.py:222:display Error rendering template (/opt/promenade/promenade/templates/roles/genesis/etc/kubernetes/manifests/bootstrap-armada.yaml): No match found for path HostSystem:images.monitoring_image
+ error 'generating genesis'
+ set +x
Error when generating genesis.
+ exit 1
+ clean
+ set +x
To remove files generated during this script's execution, delete /root/deploy.
This VM is disposable. Re-deployment in this same VM will lead to unpredictable results.

**Comment by tbfleming** [comment]
We haven't released anything with the name "airship-in-a-bottle". Maybe ask the people who did.

**Comment by jgiszczak** [comment]
We also haven't released any sort of Kubernetes support, or anything called "promenade".

**Comment by swainamar** [comment]
I am sorry. Could be mistakenly reached to this site. Please disregards this request.
